name: CI/CD
on:
  push:
    branches: [Develop]
jobs:
  Build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
        env:
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
         name: ${{ github.event.repository.name }}
         path: build/libs
         
  Deploy:
   name: Deploy Docker Image to JFROG 
   needs: Build
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/download-artifact@v3
      with:
          name: ${{ github.event.repository.name }}
          path: build/libs
 
    - uses: docker/login-action@v1
      with: 
              registry: ${{ secrets.JFROG_URL }}
              username: ${{ secrets.JFROG_USER  }}
              password: ${{ secrets.JFROG_PASSWORD }}
    - name: Docker
      run: |
       docker build . --tag magmutualartifactory-docker-local.jfrog.io/${{ github.event.repository.name }}:${{ github.sha }}
       docker push magmutualartifactory-docker-local.jfrog.io/${{ github.event.repository.name }}:${{ github.sha }}
