name: CI
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
         name: hello-world
         path: build/libs
         
  deploy:
   name: Deploy
   needs: Build
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/download-artifact@v3
      with:
          name: hello-world
          path: build/libs
 
    - uses: docker/login-action@v1
      with: 
              registry: ${{ secrets.JFROG_URL }}
              username: ${{ secrets.JFROG_USER  }}
              password: ${{ secrets.JFROG_PASSWORD }}
    - name: Extract latest tag
      run: |
        GIT_TAG=$GITHUB_REF_NAME
    - name: Docker
      run: |
       docker build -t magmutualartifactory-docker-local.jfrog.io/docker-local:${{ github.sha }} .
       docker push magmutualartifactory-docker-local.jfrog.io/docker-local:${{ github.sha }}
