name: CI
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
         name: hello-world
         path: build/libs
         
  deploy:
   name: Deploy
   needs: gradle
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/download-artifact@v3
      with:
          name: hello-world
          path: build/libs

    - uses: jfrog/setup-jfrog-cli@v2
      env:
    # JFrog platform url (for example: https://acme.jfrog.io) 
       JF_URL: ${{ secrets.JFROG_URL }}
    
    # Basic authentication credentials
       JF_USER: ${{ secrets.JFROG_USER }}
       JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

    - run: |
       docker login magmutualartifactory-docker-local.jfrog.io
