name: CI
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          cache: gradle
      - uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Upload build JAR
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  docker:
    runs-on: ubuntu-latest
    needs: gradle
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Download gradle build result
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - run: pwd .
      - run: ls build
